[tool.poetry]
name = "bookmark"
version = "0.1.0"
description = ""
authors = ["Ohjinseo <dhwlstj@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
